package edu.kit.kastel.sdq.eclipse.grading.api.backendstate;

public enum State {
	ERROR_STATE, //
	NO_STATE, //
	COURSE_SET, //
	COURSE_EXERCISE_SET, //
	COURSE_EXERCISE_SUBMISSION_SET, //
	COURSE_EXERCISE_SUBMISSION_SET_SUBMISSION_STARTED, //
	COURSE_EXERCISE_SUBMISSION_SET_SUBMISSION_SAVED
}
